# DON'T EDIT THIS!
#
# Codecrafters relies on this file being intact to run tests successfully. Any changes
# here will not reflect when CodeCrafters tests your code, and might even cause build
# failures.
#
# DON'T EDIT THIS!

name: codecrafters-shell
version: 0.1.0.0
license: BSD3

dependencies:
  - base >= 4.19 && < 5
  - process
  - directory
  - filepath

executables:
  codecrafters-shell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
