hints:
  - title_markdown: "How do I read the user's command?"
    body_markdown: |-
      Use the [`Scanner`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Scanner.html) class with [`System.in`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/System.html#in):
      ```java
      import java.util.Scanner;

      // Captures the user's command in the "command" variable
      Scanner scanner = new Scanner(System.in);
      String command = scanner.nextLine();
      ```

      The `nextLine()` method waits for the user to enter a command and returns it as a string.

  - title_markdown: 'How do I print the command not found message?'
    body_markdown: |-
      Use [`System.out.println()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/PrintStream.html#println(java.lang.String)):
      ```java
      // Prints the "<command>: command not found" message
      System.out.println(command + ": command not found");
      ```
