hints:
  - title_markdown: "How do I read the user's command?"
    body_markdown: |-
      Use the [`fgets()`](https://man7.org/linux/man-pages/man3/fgets.3.html) function:
      ```c
      #include <stdio.h>

      // Captures the user's command in the "command" variable
      char command[1024];
      fgets(command, sizeof(command), stdin);
      ```

      The `fgets()` function waits for the user to enter a command and stores it (including a newline) in the `command` buffer.

  - title_markdown: 'How do I print the command not found message?'
    body_markdown: |-
      Use the [`printf()`](https://man7.org/linux/man-pages/man3/printf.3.html) function:
      ```c
      #include <string.h>

      // Remove the trailing newline
      command[strcspn(command, "\n")] = '\0';
      
      // Prints the "<command>: command not found" message
      printf("%s: command not found\n", command);
      ```

      The code above uses [`strcspn()`](https://man7.org/linux/man-pages/man3/strcspn.3.html) to find and remove the trailing newline before printing.
