hints:
  - title_markdown: "How do I read the user's command?"
    body_markdown: |-
      Use the [`std::getline()`](https://en.cppreference.com/w/cpp/string/basic_string/getline) function:
      ```cpp
      #include <iostream>
      #include <string>

      // Captures the user's command in the "command" variable
      std::string command;
      std::getline(std::cin, command);
      ```

      The `std::getline()` function waits for the user to enter a command and stores it in the `command` string.

  - title_markdown: 'How do I print the command not found message?'
    body_markdown: |-
      Use [`std::cout`](https://en.cppreference.com/w/cpp/io/cout):
      ```cpp
      // Prints the "<command>: command not found" message
      std::cout << command << ": command not found" << std::endl;
      ```

      The code above uses the stream insertion operator (`<<`) to output the message to the console.
